include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false
    prefer_single_quotes: true
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
